os: osx

language: objective-c

branches:
  only:
    - master

install:
  - scripts/install_sketch.sh

script:
  - mkdir -p out
  - scripts/export_images.sh out/images images.sketch
  - scripts/import_to_ios.sh

notifications:
  email: false
