os: osx

language: objective-c

install:
  - script/install_sketch.sh

script:
  - mkdir out
  - script/export_images.sh out

addons:
  artifacts: true
  s3_region: "us-west-1" # defaults to "us-east-1"

notifications:
  email: false
